apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-bucket
  name: thanos-bucketweb
  namespace: test
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: thanos-bucket
