apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-querier
  namespace: test
spec:
  serviceName: thanos-querier
  replicas: 1
  selector:
    matchLabels:
      app: thanos-querier
  template:
    metadata:
      labels:
        app: thanos-querier
    spec:
      containers:
      - args:
        - query
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:9090
        - --log.level=info
        - --query.replica-label=prometheus_replica
        - --query.replica-label=rule_replica
        - --store=dnssrv+_grpc._tcp.thanos-store.thanos.svc.cluster.local
        - --store=prometheus-operator-prometheus-thanos.operator.svc.cluster.local:10901
        image: quay.io/thanos/thanos:v0.17.0
        name: thanos-query
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 9090
          name: http
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /-/ready
            port: 9090
            scheme: HTTP
          periodSeconds: 5
        resources: {}
        volumeMounts:
        - name: thanos-querier-data
          mountPath: /persistent
        terminationMessagePolicy: FallbackToLogsOnError
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
  volumeClaimTemplates:
  - metadata:
      name: thanos-querier-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
