apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem
