apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: test
spec:
  serviceAccountName: prometheus
  containers:
  - args:
    - sidecar
    - --prometheus.url=http://localhost:9090
    - --grpc-address=0.0.0.0:10901
    - --http-address=0.0.0.0:10902
    - --tsdb.path=/prometheus/
    image: quay.io/thanos/thanos:v0.17.0
    imagePullPolicy: IfNotPresent
    name: thanos-sidecar
    ports:
    - containerPort: 10901
      name: grpc
      protocol: TCP
    - containerPort: 10902
      name: http
      protocol: TCP
  serviceMonitorSelector:
    matchLabels:
      prometheus: prometheus
  resources:
    requests:
      memory: 400Mi
