apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: prometheus
  name: prometheus
  namespace: test
spec:
  endpoints:
  - path: /metrics
    port: web
  namespaceSelector:
    matchNames:
    - test
  selector:
    matchLabels:
      prometheus: prometheus
