### service for Prometheus
apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: prometheus
  name: prometheus
spec:
  type: NodePort
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus

---
### service for sidecar 

apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-querier
  name: prometheus-thanos
  namespace: test
spec:
  ports:
  - name: grpc
    port: 10901
    protocol: TCP
    targetPort: grpc
  selector:
    prometheus: prometheus
  type: NodePort

