apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store
  namespace: test
  labels:
    app: thanos-store
spec:
  serviceName: thanos-store
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store
  template:
    metadata:
      labels:
        app: thanos-store
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: thanos-store
        image: quay.io/thanos/thanos:v0.17.0
        args:
        - store
        - --log.level=debug
        - --data-dir=/var/thanos/store
        - --objstore.config-file=/config/thanos-store.yml
        ports:
        - name: http
          containerPort: 9090
        - name: grpc
          containerPort: 10901
        volumeMounts:
        - name: config
          mountPath: /config/
          readOnly: true
        - name: data
          mountPath: /var/thanos/store
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: thanos-store-config
  volumeClaimTemplates:
  - metadata:
      labels:
        app: thanos-store
      name: thanos-store
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-store-config
  namespace: test
data:
  thanos-store.yml: |-
    type: FILESYSTEM
    config:
      directory: /home/mohan/tthanos
      
