apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: prometheus
  name: thanos-receiver
  namespace: test
spec:
  endpoints:
  - port: http
  namespaceSelector:
    matchNames:
    - test
  selector:
    matchLabels:
      app: thanos-receiver
