apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: thanos-receiver
  name: thanos-receiver
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-receiver
  serviceName: thanos-receiver
  template:
    metadata:
      labels:
        app: thanos-receiver
    spec:
      containers:
      - args:
        - receive
        - --log.level=info
        - --tsdb.path=/prometheus
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:9090
        - --remote-write.address=0.0.0.0:19291
        - --receive.replication-factor=1
        - --objstore.config-file=/config/thanos-store.yml
        - --receive.local-endpoint=thanos-receive.depl.svc.cluster.local:10901
        image: quay.io/thanos/thanos:v0.17.0
        name: thanos-receive
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 9090
          name: http
        - containerPort: 19291
          name: remote-write
        resources:
          limits:
            cpu: 0.42
            memory: 420Mi
          requests:
            cpu: 0.123
            memory: 123Mi
        volumeMounts:
        - name: config
          mountPath: /config/
          readOnly: true
        - name: data
          mountPath: /var/thanos/receiver
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: thanos-store-config
  volumeClaimTemplates:
  - metadata:
      labels:
        app: thanos-receiver
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
