apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
  namespace: test
spec:
  type: NodePort
  ports:
    - name: web
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio
