apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: test
spec:
  type: NodePort
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio
